name: bloque_clase
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - jupyter
  - jupyterlab
  - openpyxl
  - matplotlib
  - seaborn
  - scikit-learn
  - pip
  - pip:
    - pytest